Update scripts

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -26,8 +26,8 @@ jobs:
       - name: Get modpack info
         id: info
         run: |
-            if [ ! -f /pax/modpack/manifest.json ]; then
-                echo "::error::Could not find the `manifest.json`." && exit 1
+            if [ ! -f pax/modpack/manifest.json ]; then
+                echo "::error::Could not find manifest.json" && exit 1
             fi
             manifestjson=`cat pax/modpack/manifest.json`
             projectname=`echo $(jq -r '.name' <<< "$manifestjson")`
