Add modpack downloader

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -26,16 +26,16 @@ jobs:
       - name: Get modpack info
         id: info
         run: |
-            if [ ! -f pax/modpack/manifest.json ]; then
-                echo "::error::Could not find manifest.json" && exit 1
-            fi
-            manifestjson=`cat pax/modpack/manifest.json`
-            projectname=`echo $(jq -r '.name' <<< "$manifestjson")`
-            echo "projectname=$projectname" >> $GITHUB_OUTPUT
-            packversion=`echo $(jq -r '.version' <<< "$manifestjson")`
-            echo "packversion=$packversion" >> $GITHUB_OUTPUT
-            mcversion=`echo $(jq -r '.minecraft.version' <<< "$manifestjson")`
-            echo "mcversion=$mcversion" >> $GITHUB_OUTPUT
+          if [ ! -f pax/modpack/manifest.json ]; then
+            echo "::error::Could not find manifest.json" && exit 1
+          fi
+          manifestjson=`cat pax/modpack/manifest.json`
+          projectname=`echo $(jq -r '.name' <<< "$manifestjson")`
+          echo "projectname=$projectname" >> $GITHUB_OUTPUT
+          packversion=`echo $(jq -r '.version' <<< "$manifestjson")`
+          echo "packversion=$packversion" >> $GITHUB_OUTPUT
+          mcversion=`echo $(jq -r '.minecraft.version' <<< "$manifestjson")`
+          echo "mcversion=$mcversion" >> $GITHUB_OUTPUT
       - name: Get tag
         id: version
         uses: "WyriHaximus/github-action-get-previous-tag@v1"
@@ -95,14 +95,20 @@ jobs:
           CURSEFORGE_API_KEY: ${{ secrets.CF_API_KEY }}
         run: |
           mkdir ${GITHUB_WORKSPACE}/downloader
-          java -jar pax/ModpackDownloader-1.0-SNAPSHOT-jar-with-dependencies.jar pax/modpack downloader
-          cd downloader/mods
+          cd pax/
+          modpack_downloader_version=$(grep -Po '(?<="ModpackDownloader": ")[^"]*' setup.json)
+          curl https://github.com/juraj-hrivnak/ModpackDownloader/releases/download/v$modpack_downloader_version/ModpackDownloader-$modpack_downloader_version-jar-with-dependencies.jar -o ModpackDownloader-$modpack_downloader_version-jar-with-dependencies.jar -L -J
+          java -jar ModpackDownloader-$modpack_downloader_version-jar-with-dependencies.jar modpack downloader
+          cd ../downloader/mods
           find . -type f -name '*.zip' -exec rm {} +
           mv ../mods ../../mods
       - name: Export serverpack
         run: |
-          cd pax/serverpack/
-          java -jar ServerPackCreator-3.0.0-alpha.12.jar -cli
+          cd pax/
+          server_pack_creator_version=$(grep -Po '(?<="ServerPackCreator": ")[^"]*' setup.json)
+          cd serverpack/
+          curl https://github.com/Griefed/ServerPackCreator/releases/download/$server_pack_creator_version/ServerPackCreator-$server_pack_creator_version.jar -o ./serverpack/ServerPackCreator-$server_pack_creator_version.jar -L -J
+          java -jar ServerPackCreator-$server_pack_creator_version.jar -cli
       - name: Rename zip
         run: |
           mv pax/serverpack/server-packs/_server_pack.zip pax/serverpack/server-packs/${{ needs.modpack-info.outputs.projectname }}-v${{ needs.modpack-info.outputs.packversion }}-build.${{ github.run_number }}-Server-Pack.zip
